#!/bin/bash

echo "Executing post commit " >>/tmp/postcommit.log
branch=$(git rev-parse --abbrev-ref HEAD)
GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git push origin ${branch}